### PR TITLE
Fix Darwin build

### PR DESCRIPTION
**Pull request by altendky**
This is being built off of https://github.com/altendky/pyqt-plugins/pull/14.  Thanks to @jayvdb for getting this started and pushing me to continue.

### CODE REVIEW

**Comment by altendky** [comment]
@jayvdb, if you had any time to look at the errors here, that could help.  I tried to get into my MacStadium system but had TeamViewer issues and vnc is unusably slow for some reason.  So, I'll have to fix that before I have any interactive debugging.

**Comment by jayvdb** [comment]
Sure, will do today

**Comment by jayvdb** [comment]
I've fiddled a bit with the qmlscene test, and the error causing it to fail is that plugin pyqt5qmlplugin cant be loaded.  It does not appear that libpyqt5qmlplugin.dylib is being built.

**Comment by altendky** [comment]
```
2021-04-29T16:00:31.3932460Z rm -f libpyqt5qmlplugin.dylib
2021-04-29T16:00:31.3968100Z /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -stdlib=libc++ -headerpad_max_install_names  -arch x86_64 -Wl,-syslibroot,/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/runner/work/pyqt-plugins/pyqt-plugins/build/pyqt5_plugins-wvkovtyz/qt/5.14.1/clang_64/lib -single_module -dynamiclib -o libpyqt5qmlplugin.dylib pluginloader.o moc_pluginloader.o  -F/Users/runner/work/pyqt-plugins/pyqt-plugins/build/pyqt5_plugins-wvkovtyz/qt/5.14.1/clang_64/lib -L/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib -lpython3.6m -framework QtGui -framework AppKit -framework Metal -framework QtQml -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL    
2021-04-29T16:00:31.4138890Z ld: warning: dylib (/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/libpython3.6m.dylib) was built for newer macOS version (10.14) than being linked (10.13)
```

So we've got `-o libpyqt5qmlplugin.dylib` and then `libpython3.6m.dylib) was built for newer macOS version (10.14) than being linked (10.13)`.  The first two lines are the only ones referencing `qmlplugin` in the entire log.  There is no Qt directory at all in the resulting wheels.

(macOS on the left, published Linux on the right)
image

I'll see where I can get from here.  Thanks.

**Comment by altendky** [comment]
https://github.com/altendky/pyqt-plugins/pull/15/checks?check_run_id=2492495525#step:14:252
```
loaded library "/Users/runner/work/pyqt-plugins/pyqt-plugins/.tox/py35/lib/python3.5/site-packages/pyqt5_plugins/examples/libpyqt5qmlplugin.dylib"
Cannot load library libpython3.5m.dylib: (dlopen(libpython3.5m.dylib, 9): image not found)
```

Maybe https://github.com/actions/setup-python is getting us a statically linked Python rather than dynamically linked?  I think that using the Python Docker images addresses this for Linux.

**Comment by jayvdb** [comment]
I doubt it is a statically linked Python.  Try installing https://formulae.brew.sh/formula/findutils on the VM , running `sudo gupdatedb` and then `locate ...`.  If it does appear, I suspect that LD_LIBRARY_PATH may need to explicitly refer to the directory the lib.

**Comment by altendky** [comment]
Now that I put that in, I'm thinking that may take awhile.  Might be worth just doing a `find /Users/runner/hostedtoolcache/Python -iname '*.dylib'`?  I'll give that a try.

https://github.com/altendky/pyqt-plugins/pull/15/checks?check_run_id=2493111767

```
/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/libpython2.7.dylib
/Users/runner/hostedtoolcache/Python/3.7.10/x64/lib/libpython3.7m.dylib
/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/libpython3.6m.dylib
/Users/runner/hostedtoolcache/Python/3.9.4/x64/lib/libpython3.9.dylib
/Users/runner/hostedtoolcache/Python/3.5.10/x64/lib/libpython3.5m.dylib
/Users/runner/hostedtoolcache/Python/3.8.9/x64/lib/libpython3.8.dylib
```

So, off to check what I'm doing in Linux for `LD_LIBRARY_PATH`...

**Comment by altendky** [comment]
Two passing now, one failing...

**Comment by jayvdb** [comment]
If you have some passing, perhaps you could add skips for the others on Mac only, allowing merging, and publishing of the wheels for all these projects.  Then it will be much easier to debug the remaining problems.

**Comment by altendky** [comment]
The reason that there even are four layers is that I ran out of space on PyPI.  This separation allows me to release three of the layers without much concern for that, but the base qt-applications layer is still big and needs to be gotten right.  But, for local testing, the wheels from each layer can be downloaded from the Actions artifacts and installed that way to save building.  I would like at some point to be able to do the same in these builds, but haven't gotten there yet.

I'm going to look back around for remaining handling in Linux that isn't being done in macOS.

**Comment by jayvdb** [comment]
iirc, in my PR I disabled 5.14.0/1 on Mac. IMO it isnt worth getting those working.

**Pull request merged**
